# ============================================================
# Exp003
# High Resolution + Hard Negative
# Model: YOLO11s
# ============================================================

model: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/yolo11s.pt

data: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/data/dataset.yaml


# ============================================================
# Training
# ============================================================

epochs: 100

# 核心改动：640 -> 960
imgsz: 960

# 960 分辨率显存占用明显增加
# RTX 4060 Laptop 8GB 先从 4 开始
batch: 4

workers: 4

device: 0


# ============================================================
# Optimizer
# ============================================================

optimizer: auto


# ============================================================
# Reproducibility
# ============================================================

seed: 42

deterministic: true


# ============================================================
# Early Stopping
# ============================================================

patience: 30


# ============================================================
# Save / Validation
# ============================================================

save: true

save_period: -1

val: true

plots: true

amp: true

cache: false


# ============================================================
# Data Augmentation
#
# 为了做干净对比，
# 本轮增强参数保持和之前一致。
# ============================================================

hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4

degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0

flipud: 0.0
fliplr: 0.5

mosaic: 1.0

mixup: 0.0

copy_paste: 0.0


# ============================================================
# Output
# ============================================================

project: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/runs/detect

name: Exp003_HighRes_HardNegative_YOLO11s_960

exist_ok: false
