# ============================================================
# Exp002
# High Resolution + Hard Negative
# YOLO11s
# ============================================================

model: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/yolo11s.pt

data: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/data/dataset.yaml


# ============================================================
# Training
# ============================================================

epochs: 100

imgsz: 960

# 960 分辨率显存占用会明显增加
# 先使用 batch=4，比直接 batch=8 更稳
batch: 4

workers: 4

device: 0


# ============================================================
# Optimizer
# ============================================================

optimizer: auto


# ============================================================
# Reproducibility
# ============================================================

seed: 42

deterministic: true


# ============================================================
# Early stopping
# ============================================================

patience: 30


# ============================================================
# Save / Validation
# ============================================================

save: true

save_period: -1

val: true

plots: true

amp: true

cache: false


# ============================================================
# Data augmentation
#
# 第一轮 Exp002 主要研究：
#
# 1. 640 -> 960
# 2. 加入 Hard Negative
#
# 所以增强策略先不要大改，
# 保持和 baseline 尽可能一致。
# ============================================================

hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4

degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0

flipud: 0.0
fliplr: 0.5

mosaic: 1.0

mixup: 0.0

copy_paste: 0.0


# ============================================================
# Output
# ============================================================

project: E:/workspace/01_Projects/AI_Vision_Learning/Fruit_YOLO/runs/detect

name: Exp002_HighRes_HardNegative_YOLO11s_960

exist_ok: false
